apiVersion: v1
kind: Secret
metadata:
  name: governify-secrets
  namespace: governify-production
type: Opaque
stringData:
  jwt_secret: REPLACE_WITH_AT_LEAST_32_RANDOM_BYTES
  authenticator_admin_password: REPLACE_WITH_A_RANDOM_ADMIN_PASSWORD
  scope_manager_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  registry_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  computer_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  fetcher_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  reporter_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  director_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  join_backend_client_secret: REPLACE_WITH_A_RANDOM_CLIENT_SECRET
  influx_token: apiv3_REPLACE_WITH_AT_LEAST_16_RANDOM_BYTES
  influx_admin_token.json: |
    {
      "token": "apiv3_REPLACE_WITH_THE_SAME_TOKEN",
      "name": "governify-admin"
    }
  grafana_user: governify-admin
  grafana_password: REPLACE_WITH_A_RANDOM_PASSWORD
  oidc_client_id: REPLACE_WITH_OIDC_CLIENT_ID
  oidc_client_secret: REPLACE_WITH_OIDC_CLIENT_SECRET
  github_app_id: REPLACE_WITH_GITHUB_APP_ID
  github_app_client_id: REPLACE_WITH_GITHUB_APP_CLIENT_ID
  github_app_client_secret: REPLACE_WITH_GITHUB_APP_CLIENT_SECRET
  github_app_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_WITH_GITHUB_APP_PRIVATE_KEY
    -----END RSA PRIVATE KEY-----
