apiVersion: v1
kind: ServiceAccount
metadata:
  name: governify-headlamp
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: governify-headlamp-admin
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: governify-headlamp-admin-token
$patch: delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: governify-headlamp-admin
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governify-headlamp
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: governify-headlamp
$patch: delete
